wip: Tweaking scripts for 2.80
The materials don't work yet as I'm battling the following:

```
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "Text", line 732, in <module>
  File "Text", line 719, in generate_spaceship
  File "Text", line 463, in create_materials
  File "Text", line 443, in set_hull_mat_basics
  File "Text", line 430, in add_hull_normal_map
AttributeError: 'Material' object has no attribute 'texture_slots'
```

Need to look up some tutorials to see how this to do this the 2.8 way